server:
 port: 8888
spring:
 application:
 name: configserver
 cloud:
 config:
 server:
 git:
 uri: https://github.com/luohuijuan/repository.git
 searchPaths: config-repo
 username: 1078258449@qq.com
 password: luohuijuan@123
 label: master
eureka:
 client:
 serviceUrl:
 defaultZone: http://localhost:8761/eureka/